version: '3.9'

services:
  web:
    build: .
    command: gunicorn Servidor.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db

  monitor:
    build: .
    command: python Aplicacion/monitoreo.py
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: valmo_db
      MYSQL_USER: valmo_user
      MYSQL_PASSWORD: valmo_pass
      MYSQL_ROOT_PASSWORD: root_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
