# Generated by Django 5.2.4 on 2025-07-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('estatus', models.IntegerField(default=0)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
